'use strict';

/*
 * server.js
 * ---------
 * Zero-dependency Node HTTP server. Serves the SPA and a small JSON API for the
 * negotiation engine. No `npm install` required — runs on a clean Node 18+.
 *
 * Optional: if ANTHROPIC_API_KEY is set, opponent dialogue is generated by the
 * LLM in-character; otherwise the engine's templated lines are used. The game
 * STATE (meters, offers, scoring) is always driven by the deterministic engine,
 * so the simulator is fair and reproducible either way.
 */

const http = require('http');
const fs = require('fs');
const path = require('path');
const { scenarios } = require('./data/scenarios');
const engine = require('./engine/engine');
const { analyze } = require('./engine/techniques');
const ai = require('./engine/ai');

const PORT = process.env.PORT || 3000;
const PUBLIC = path.join(__dirname, 'public');

// In-memory session store (fine for a training tool / single instance).
const sessions = new Map();

const MIME = {
  '.html': 'text/html; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.js': 'text/javascript; charset=utf-8',
  '.json': 'application/json; charset=utf-8',
  '.svg': 'image/svg+xml',
  '.ico': 'image/x-icon',
};

function sendJSON(res, code, obj) {
  const body = JSON.stringify(obj);
  res.writeHead(code, { 'Content-Type': 'application/json; charset=utf-8' });
  res.end(body);
}

function readBody(req) {
  return new Promise((resolve, reject) => {
    let data = '';
    req.on('data', (c) => {
      data += c;
      if (data.length > 1e6) req.destroy();
    });
    req.on('end', () => {
      try { resolve(data ? JSON.parse(data) : {}); }
      catch (e) { reject(e); }
    });
    req.on('error', reject);
  });
}

function publicScenario(s, lang) {
  return {
    id: s.id,
    icon: s.icon,
    difficulty: s.difficulty,
    title: s.title[lang],
    role: s.role[lang],
    counterpart: { name: s.counterpart.name[lang], persona: s.counterpart.persona[lang] },
    headline: s.headline.unit[lang],
    briefing: s.briefing[lang],
    batna: s.playerBatna.note[lang],
    target: s.playerTarget,
    reservation: s.playerReservation,
  };
}

function publicState(sess) {
  const s = sess.state;
  return {
    trust: Math.round(s.trust),
    tension: Math.round(s.tension),
    info: Math.round(s.info),
    leverage: Math.round(engine.flexibility(sess) * 100),
    offerOpp: s.offerOpp,
    offerPlayer: s.offerPlayer,
    interestsFound: s.interestsFound.length,
    status: s.status,
    turn: sess.turn,
    maxTurns: sess.maxTurns,
  };
}

// ---- API handlers -----------------------------------------------------------

async function handleApi(req, res, url) {
  const lang = (url.searchParams.get('lang') || 'ru') === 'en' ? 'en' : 'ru';

  if (req.method === 'GET' && url.pathname === '/api/scenarios') {
    return sendJSON(res, 200, { scenarios: scenarios.map((s) => publicScenario(s, lang)) });
  }

  if (req.method === 'POST' && url.pathname === '/api/start') {
    const body = await readBody(req);
    const sess = engine.createSession(body.scenarioId, lang);
    sessions.set(sess.id, sess);
    const sc = scenarios.find((s) => s.id === body.scenarioId);
    const greeting = lang === 'ru'
      ? `Здравствуйте. Я ${sc.counterpart.name.ru}. Наше стартовое предложение — ${sess.state.offerOpp}${sc.headline.unit.ru}. С чего начнём?`
      : `Hello. I'm ${sc.counterpart.name.en}. Our opening position is ${sess.state.offerOpp}${sc.headline.unit.en}. Where shall we start?`;
    return sendJSON(res, 200, {
      sessionId: sess.id,
      scenario: publicScenario(sc, lang),
      state: publicState(sess),
      greeting,
    });
  }

  if (req.method === 'POST' && url.pathname === '/api/say') {
    const body = await readBody(req);
    const sess = sessions.get(body.sessionId);
    if (!sess) return sendJSON(res, 404, { error: 'session not found' });
    if (sess.state.status !== 'active') return sendJSON(res, 400, { error: 'session finished' });

    const text = String(body.text || '').slice(0, 800);
    const analysis = analyze(text);
    sess.turn += 1;

    const result = engine.applyMove(sess, analysis, text);

    // End if out of turns without a deal.
    let timeout = false;
    if (sess.state.status === 'active' && sess.turn >= sess.maxTurns) {
      sess.state.status = 'breakdown';
      result.closed = true;
      timeout = true;
    }

    // Record the player's turn first so AI backends can read it from the log.
    sess.log.push({ role: 'player', text, analysis: { tags: analysis.tags, primary: analysis.primary, argQuality: analysis.argQuality } });

    // Opponent reply text: real model (CLI/API) if enabled, else templated.
    let reply = engine.renderLine(sess, result.reaction, result.closed);
    const real = await ai.getOpponentReply(sess, analysis, result, reply).catch(() => null);
    if (real) reply = real;
    if (timeout) reply = lang === 'ru'
      ? 'У нас вышло время на сегодня. Предлагаю вернуться позже — договориться так и не удалось.'
      : "We're out of time for today. Let's revisit later — we couldn't reach agreement.";

    sess.log.push({ role: 'opp', text: reply });

    const payload = {
      reply,
      analysis: {
        tags: analysis.tags,
        primary: analysis.primary,
        argQuality: analysis.argQuality,
        spin: analysis.spin,
        flags: analysis.flags,
      },
      deltas: result.deltas,
      state: publicState(sess),
      closed: result.closed,
    };
    if (result.closed) payload.debrief = engine.scoreSession(sess);
    return sendJSON(res, 200, payload);
  }

  if (req.method === 'POST' && url.pathname === '/api/hint') {
    // Contextual coaching hint based on current state (no spoilers on numbers).
    const body = await readBody(req);
    const sess = sessions.get(body.sessionId);
    if (!sess) return sendJSON(res, 404, { error: 'session not found' });
    const s = sess.state;
    const sc = scenarios.find((x) => x.id === sess.scenarioId);
    let hint;
    const ru = lang === 'ru';
    if (s.info < 40) hint = ru
      ? 'Вы почти не знаете, что движет оппонентом. Задайте вопрос: «Что для вас важнее всего в этой сделке?»'
      : 'You barely know what drives them. Ask: "What matters most to you in this deal?"';
    else if (s.tension > 60) hint = ru
      ? 'Напряжение высокое — уступки заморожены. Признайте их позицию: «Понимаю, откуда вы идёте…»'
      : 'Tension is high — concessions are frozen. Acknowledge them: "I understand where you\'re coming from…"';
    else if (sess.metrics.objectiveCriteria === 0) hint = ru
      ? 'Подкрепите позицию объективным критерием: сошлитесь на рыночные данные или стандарт.'
      : 'Back your position with an objective criterion: cite market data or a standard.';
    else if (s.tradeoffsUsed.length === 0 && s.info > 40) hint = ru
      ? `Вы знаете их интересы — предложите размен: «Если мы дадим ${sc.tradeoffs.ru[0].toLowerCase()}, сможете подвинуться по цене?»`
      : `You know their interests — propose a trade: "If we offer ${sc.tradeoffs.en[0].toLowerCase()}, can you move on price?"`;
    else hint = ru
      ? 'Хорошая траектория. Двигайтесь к закрытию: назовите число и предложите зафиксировать сделку.'
      : 'Good trajectory. Move to close: name a number and propose to lock the deal.';
    return sendJSON(res, 200, { hint });
  }

  return sendJSON(res, 404, { error: 'not found' });
}

// ---- Static file serving ----------------------------------------------------

function serveStatic(req, res, url) {
  let p = url.pathname === '/' ? '/index.html' : url.pathname;
  const filePath = path.join(PUBLIC, path.normalize(p).replace(/^(\.\.[/\\])+/, ''));
  if (!filePath.startsWith(PUBLIC)) { res.writeHead(403); return res.end('forbidden'); }
  fs.readFile(filePath, (err, data) => {
    if (err) { res.writeHead(404); return res.end('not found'); }
    const ext = path.extname(filePath).toLowerCase();
    res.writeHead(200, { 'Content-Type': MIME[ext] || 'application/octet-stream' });
    res.end(data);
  });
}

const server = http.createServer(async (req, res) => {
  try {
    const url = new URL(req.url, `http://${req.headers.host}`);
    if (url.pathname.startsWith('/api/')) return await handleApi(req, res, url);
    return serveStatic(req, res, url);
  } catch (e) {
    sendJSON(res, 500, { error: 'server error', detail: String(e && e.message || e) });
  }
});

server.listen(PORT, () => {
  console.log(`\n  🤝  Negotiation Simulator running`);
  console.log(`      http://localhost:${PORT}`);
  console.log(`      opponent dialogue: ${ai.describeMode()}`);
  const warm = ai.warmup();
  if (warm) console.log(`      ${warm}  (watch it live: tmux attach -t ${require('./engine/claude-tmux').SESSION})`);
  console.log('');
});
